/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [5.23MB] > C:\Users\syed aafreen\OneDrive\Desktop\docs\main\glf\porsche_911_gt3\scene-transformed.glb [1.64MB] (69%)
Author: Outlaw Games™ (https://sketchfab.com/Outlaw_Games)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/porsche-911-gt3-593c83f3662a4a45a016f95dedd9f243
Title: Porsche 911 GT3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

 function Model(props) {
  const { nodes, materials } = useGLTF('/models/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_9.geometry} material={materials.Porsche_911GT3_2022Grille3A_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Porsche_911GT3_2022Grille4A_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Porsche_911GT3_2022Grille5A_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Porsche_911GT3_2022BadgeA_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Porsche_911GT3_2022Base_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Porsche_911GT3_2022Carbon1_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Porsche_911GT3_2022Coloured_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Porsche_911GT3_2022Grille1A_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Porsche_911GT3_2022Grille2A_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.Porsche_911GT3_2022Grille6A_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Porsche_911GT3_2022Grille7A_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.Porsche_911GT3_2022InteriorTillingA_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Porsche_911GT3_2022LightA_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Porsche_911GT3_2022Paint_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.Porsche_911GT3_2022Window_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.RED_GLASS} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.Porsche_911GT3_2022ManufacturerPlateA_Material} rotation={[0.009, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.Porsche_911GT3_2022Paint_Material} scale={0.01} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.Porsche_911GT3_2022InteriorA_Material} scale={0.01} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.Porsche_911GT3_2022_Wheel1A_3D_3DWheel1A_Material} position={[0.007, 0.003, 0.012]} rotation={[0, 0, 0.017]} scale={0.01} />
      <mesh geometry={nodes.Object_3385.geometry} material={materials.Porsche_911GT3_2022_CallipersCalliperA_Zone_Material} position={[0.007, 0.003, 0.012]} rotation={[0, 0, 0.017]} scale={0.01} />
    </group>
  )
}

export default Model;

useGLTF.preload('/models/scene-transformed.glb')
