/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [118.96KB] > C:\Users\syed aafreen\OneDrive\Desktop\docs\main\glf\2005_porsche_911_gt2\scene-transformed.glb [315.04KB] (-165%)
Author: OUTPISTON (https://sketchfab.com/outpiston)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2005-porsche-911-gt2-b85a2e1464944eb280e5f683dd528776
Title: 2005 Porsche 911 GT2
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Vehicle_Exterior_mm_tyre} position={[-0.863, 0.321, 1.168]} rotation={[Math.PI / 2, 0, 0]} scale={[-1.083, 1.083, 1.083]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Vehicle_Exterior_mm_rotor} position={[-0.863, 0.321, 1.168]} rotation={[Math.PI / 2, 0, 0]} scale={[-1.083, 1.083, 1.083]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Vehicle_Exterior_mm_misc} position={[-0.863, 0.321, 1.168]} rotation={[Math.PI / 2, 0, 0]} scale={[-1.083, 1.083, 1.083]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Vehicle_Exterior_mm_cab} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.Vehicle_Exterior_mm_chassis} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
